version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosysyem: "nuget"
    directory: "/code/"
    schedule: 
      interval: "weekly"
